osx_image: xcode7.1

os:
  - linux
  - osx

cache:
  - apt

language: cpp
sudo: required
dist: trusty

addons:
  apt:
    packages:
    - protobuf-compiler
    - libprotobuf-dev
    - libutempter-dev
    - tmux			# test suite
    - perl			# test suite

before_install:
  - if test osx = "$TRAVIS_OS_NAME"; then brew update; fi
  - if test osx = "$TRAVIS_OS_NAME"; then brew reinstall protobuf; fi
  - if test osx = "$TRAVIS_OS_NAME" && test -n "$TRAVIS_TAG"; then echo reinstall protobuf; brew rm protobuf && travis_wait 30 brew install protobuf --universal --bottle; fi
  - if test osx = "$TRAVIS_OS_NAME"; then brew reinstall tmux; fi
  - git tag
  - git fetch --tags
  - git fetch --unshallow
  - git fetch --tags
  - git tag

script:
  - ./autogen.sh
  - ./configure --enable-compile-warnings=error --enable-examples
  - git describe
  - make VERSION
  - cat ./VERSION
  - make distcheck VERBOSE=1 V=1
  - if test osx = "$TRAVIS_OS_NAME" && test -n "$TRAVIS_TAG"; then sh -c "cd macosx && env MACOSX_DEPLOYMENT_TARGET=10.10 ./build.sh && shasum -a 256 *.pkg"; fi

deploy:
  provider: releases
  api_key:
    secure: O+EmNHUQpqvrWNb1LYv5CXF9o35Mybi+Y48jr+nV3oJ+dLlwgmP71tDzARY0rEY18xT4DL9RBbl5Y74A4nZxvSMSih+VBUf+lgBhkAFkU5W1sRTaJdQVtJw6NcaeuDR/TvVMpJAPxLtHOZnmqplkQVDn4fpkweGaW0Suk7eSlibF3fd0dhoZ8sfDgWQpUW61C08ENBC9/ru01BqDcNuWA9EoS2aLRVCHKR5C02D2EFONlHTxu32X9qm5IcVrk+Zi5mmqyHk74A4a7QRJCDixKyt53LGXYpQh9flePmzSqZDKO5q3PSmWohoUzGLkKBcZit/mSd5aUeIzd7gk/YHNxGfZpGvLzjVDWpjdTXxALTcpVA64VFqLbb3P7N+zYQ7S9ZucwAz8XQ+wArqszQrLtU3vtz+AsO6dLRxAg0lLjNe084Gv0hFAn8u8HGNqBBZ177sTKoEmL3w0wdwSuxhk1aGIFnlKrzjFY57HvJlxSNupAeXqtU9/DNwLyzsnFc1qN4UKJ/hXdb5mtwug+DZy7E0RpJ/jJemfy7RjIAAZCowCLRFBxfRkY3HRaHeaF31mAogkc8FLXFjx2sR95t7GvK1AvJvHdmXs4OxjvgEVl9OI+mWQ9xMqcmjKwx5KuuAcBt8sLK7MJE6iRBwYBQ7eUQrJcYxRMN+w0vhznvLZwv8=
  skip_cleanup: true
  file: macosx/*.pkg
  on:
    repo: cgull/mosh
    tags: true
    condition: $TRAVIS_OS_NAME = osx

notifications:
  irc:
    channels:
      - "chat.freenode.net#mosh"
    skip_join: true
