os:
  - linux
  - osx

cache:
  - apt

language: cpp
sudo: required
dist: trusty

addons:
  apt:
    packages:
    - protobuf-compiler
    - libprotobuf-dev
    - libutempter-dev
    - tmux			# test suite
    - perl			# test suite

before_install:
  - if test "$TRAVIS_OS_NAME" = osx; then brew update; fi
  - if test "$TRAVIS_OS_NAME" = osx; then brew reinstall protobuf; fi
  - if test "$TRAVIS_OS_NAME" = osx; then brew reinstall tmux; fi
  - git fetch --tags --unshallow

script:
  - ./autogen.sh
  - ./configure --enable-compile-warnings=error --enable-examples
  - make distcheck VERBOSE=1 V=1
  - if test "$TRAVIS_OS_NAME" = osx -a -n "$TRAVIS_TAG"; then sh -c "cd macosx && env MACOSX_DEPLOYMENT_TARGET=10.9 ./build.sh"; fi

notifications:
  irc:
    channels:
      - "chat.freenode.net#mosh"
    skip_join: true
