os:
- linux
- osx
cache:
- apt
language: cpp
sudo: required
dist: trusty
osx_image: xcode6.4
addons:
  apt:
    packages:
    - protobuf-compiler
    - libprotobuf-dev
    - libutempter-dev
    - tmux
    - perl
before_install:
- git fetch --tags --unshallow
- |
  if test osx = "${TRAVIS_OS_NAME}"; then
    macosx/brew-deps.sh install &&
      if test -n "${TRAVIS_TAG}"; then
        travis_wait 60 macosx/brew-deps.sh package_deps
      else
        macosx/brew-deps.sh deps
      fi
  fi
before_script:
- id
- env
- git describe --long
- |
  if test osx = "${TRAVIS_OS_NAME}" && test -n "${TRAVIS_TAG}"; then
    rm -rf macosx/build-report "macosx/${TRAVIS_TAG}-osx-build-report.tbz" &&
      mkdir macosx/build-report &&
      cd macosx/build-report &&
      ../brew-deps.sh describe &&
      ../osx-xcode.sh describe &&
      tar -cjf "../${TRAVIS_TAG}-osx-build-report.tbz" . &&
      cd -
  fi
script:
- ./autogen.sh
- ./configure --enable-compile-warnings=error --enable-examples
- make distcheck VERBOSE=1 V=1
- |
  if test osx = "${TRAVIS_OS_NAME}" && test -n "${TRAVIS_TAG}"; then
    cd macosx &&
      env ZERO_AR_DATE=1 MACOSX_DEPLOYMENT_TARGET=10.10 ./build.sh &&
      shasum -a 256 "${TRAVIS_TAG}.pkg" "${TRAVIS_TAG}-osx-build-report.tbz" &&
      cd -
  fi
deploy:
  provider: releases
  api_key:
    secure: QOo8c8uvBD8Lvjk/FeyYX1it+a9Yz2ICumat0LuAglEG5BY+IZrpvRIonbcRtYcJhDuaI8MfDIvGJEusbkrGw6JB8B5fjbj0VQG9hnqbhWfRYEjzovwS7hWlT8HRqITo5Kjj6XSQytnrT0LvdjYaFGmuHlEsy3J+Th1SnrVZXoZetoIXn8FeFJxH1AZ6WQRQnohF5+g9SR0cISrAoOrxMa3kdpDTdcVgDlObM9h0v7nrpAbFA7MoIfO6lVbN4PTrGcXjSxX55Tb7v+0o5B+rehOJYKSbAkktQHlQruVPnhqDaXvyaU4TSY4luL+46dA6zPb5gFpzfMysgSFbQRGvmDqQe9fbPo1aNH/CJhfKQFavsaJkCbxe/3IOW6SFQ6ae3fkettDoVdwir4Xpln1Y7WWRBzVCNhODLvrnR1bY9Zn3ES3JehiYFW/EZdhsKAUBBKZL4eqRxofzcyJG4o0sKAWtw6R/ghFz4YN+ZUYhN49crsv6Eg3sUzpxIL5VhMPYIbYCGqT9ZyWc8cSLFtq2YDH8U7b+NPGAjnCQ2d+I8pOCLIKsEvceE9e5pyuRY1jxuxgxU5tr0gIokliMi7RwqgfM4zzz2Q2CYx94pojpvMXoWEOEuav8eCTyUv5WhzxRVTLo3HIimwlaemPurHuCxMSNln/8dfyWuAFztHNKvfc=
  file:
  - macosx/${TRAVIS_TAG}.pkg
  - macosx/${TRAVIS_TAG}-osx-build-report.tbz
  on:
    repo: cgull/mosh
    branch: mosh-1.3.0-test-build
notifications:
  irc:
    channels:
    - chat.freenode.net#mosh
    skip_join: true
